#+TITLE:     Climate Change Health Impact Assessments:  Farmer Suicide and Drought Case Study.
#+AUTHOR:  Ivan Hanigan$^1$, David Fisher$^2$, Steven McEachern$^3$
#+EMAIL:     ivan.hanigan@anu.edu.au
#+DATE:      \today
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
#+LaTeX_CLASS: beamer
#+BEAMER_HEADER_EXTRA: \institute[NCEPH]{$^1$National Centre for Epidemiology and Population Health (ANU) \\ $^2$Information Technology Services (ANU) \\ $^3$Australian Data Archives (ANU)}
#+LaTeX_CLASS_OPTIONS: [bigger]
#+latex_header: \mode<beamer>{\usetheme{Madrid}}
#+latex_header: \usepackage{verbatim}
#+latex_header: \usepackage{color}
#+latex_header: \usepackage{amsmath,amsfonts,amssymb}
#+BEAMER_FRAME_LEVEL: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+latex_header: \AtBeginSection[]{\begin{frame}<beamer>\frametitle{Topic}\tableofcontents[currentsection]\end{frame}}

* Aim
** Aim
Climate Change Health Impact Assessments (CCHIA) need
- Workflow tools for data management and analysis
- Enhanced capacity for experimentation, reviews, revisions

General approach:
- historical exposure-response functions, control covariates
- future response with changed exposures and population at risk 
** Motivating Case Study: Climate/Suicide
- Suicide has been linked to climate in a variety of studies
- Climate change impact on mental health is a gap in knowledge
- Use methods to analyse the relationship between Drought/Suicide
- Estimate future Climate Change impacts
** New Tools are Needed
- Restrictions on access to suicide data have increased recently. 
- Growing concern about the \textbf{Replicability Crisis}, (Peng 2011, \emph{Science}, 334).
- Access to data and analytic software addresses this.
- We built a safe Sever/Client IT environment. 

* Methods
** System Design
\begin{figure}[!h]
\centering
\includegraphics[width=.65\textwidth]{opensoft.pdf}
\caption{1. System Design}
\label{fig:sys}
\end{figure}
** Linux Cluster
- National Research Cloud (www.nectar.org.au/research-cloud)
- Centos 6.4 (www.centos.org)
** PostGIS Database (The Brawn)
\begin{itemize}
\item PostgreSQL 9.2 (www.postgresql.org)
\item PostGIS 2.0 (postgis.refractions.net)
\end{itemize} 

** Analysis (The Brains)
-  R language for statistical computing (www.r-project.org)
-  Rstudio server (www.rstudio.com/)
-  OpenGeo Suite (opengeo.org)


** Information Management
- Projects,UsersDB Oracle XE APEX (www.oracle.com)
- Data Catalogue (assda.anu.edu.au/ddiindex.html)

** The Client Side
-  The Kepler Project (www.kepler-project.org)
-  pgAdmin (www.pgadmin.org)
-  Git Version Control and GitHub (github.com)


** Case Study: Historical 
\begin{footnotesize}
\begin{itemize}
\item {\color{red}Restricted Health and Drought data} and 
\item {\color{blue}Less Restricted Population data} 
\end{itemize}
(Colours refer to data storage and access rules shown in Figure 1).
\begin{eqnarray*}
        log({\color{red} O_{ijk}})  & = & s({\color{red}ExposureVariable})  + {\color{blue} OtherExplanators}  \\
        & &   + AgeGroup_{i} + Sex_{j} \\
        & &   + {\color{blue} SpatialZone_{k}}  \\
        & &  + sin(Time \times 2 \times \pi) + cos(Time \times 2 \times \pi) \\
        & &  + Trend \\
        & &   + offset({\color{blue} log(Pop_{ijk})})\\
\end{eqnarray*}
\end{footnotesize}
\begin{tiny}
\noindent Where:\\
        \indent ${\color{red}O_{ijk}}$ = Outcome (counts) by Age$_{i}$, Sex$_{j}$ and SpatialZone$_{k}$ \\
        \indent {\color{red}ExposureVariable} = Data with {\color{red}Restrictive Intellectual Property~(IP)} \\
        \indent {\color{blue}OtherExplanators} = Other {\color{blue}Less Restricted}  Explanatory variables \\
        \indent s( ) = penalized regression splines \\
        \indent ${\color{blue} SpatialZone_{k}}$  = {\color{blue} Less Restricted} data representing the $SpatialZone_{k}$  \\
        \indent Trend = Longterm smooth trend(s) \\
        \indent ${\color{blue}Pop_{ijk}}$ = interpolated Census populations, by time in each group\\
\end{tiny}

** Case Study: Historical 
Hanigan et al, 2012, \emph{PNAS}, 109:
- 38 years suicide rates with drought by 11 regions, age and sex
- Estimated 9% in rural males aged 30-49 due to drought over the period
- Increased for rural males 10-29 y
- Association with hot temp + spring

** Case Study: Future 
Bambrick et al, 2008, Garnaut Review:
\begin{footnotesize}
$$Y_{ijk}=\sum_{lm}(e^{(\beta_{ijk} \times {\color{red} X_{lm}})} - 1) \times {\color{red}BaselineRate_{jkl}} \times {\color{blue} Population_{jklm}}$$
\noindent Where:\\
$\beta_{ijk}$ = the ExposureVariable coefficient for zone$_i$, age$_j$ and sex$_{k}$ \\
${\color{red}X_{lm}}$ = Projected Future ExposureVariables {\color{red} with Restrictive IP} \\
{\color{red}BaselineRate$_{jkl}$} = {\color{red}avgDeathsPerTime}/{\color{blue}avgPopPerTime} in age$_j$, sex$_k$ and zone$_l$ \\
{\color{blue}Population$_{jklm}$} = projected populations by age$_j$, sex$_k$, zone$_l$ and time$_m$ {\color{blue} (With Less Restrictions)}\\

\end{footnotesize}
* Results
** Drought-suicide response function
\begin{figure}[!h]
\centering
\includegraphics[width=.45\textwidth]{Figure1.png}
\caption{Figure1.png}
\label{fig:Figure1.png}
\end{figure}


*** COMMENT get-pic-drt-code
#+name:get-pic-drt
#+begin_src R :session *R* :tangle src/get-pic-drt.r :exports none :eval no
  ################################################################
  # name:get-pic-drt
  file.copy("/home/ivan_hanigan/Dropbox/projects/IvanPhD/Papers/Suicide and Drought in NSW/document/submission2/Figure1.tif", "Figure1.tif")
#+end_src
* Discussion
** Criticism
This model is too static, reductionist, reality is more complex. Need to work more on interactions with non-climate factors especially: 
- Natural capital
- Financial capital
- Social capital
- Physical capital and
- Human capital
* Conclusion
** Conclusion
- Drought is related to increased suicide risk in Australia
- Future Drought associated deaths can be calculated
- These estimates will be very uncertain, contentious and difficult to justify
- Data management and analysis technology such as that presented is needed to enable rigorous and transparent exploration 
** Conclusion
This system:
- Enables data analysis in a safe environment
- Allows comparison of multiple climate scenarios and assumptions
- Demonstrated with a Climate/Health Impact Assessment 
- This is Reproducible

* Acknowledgements
** Acknowledgements
\includegraphics[width=4cm]{ANU_LOGO_cmyk_56mm.png}
\includegraphics[width=2cm]{andslogo.pdf}
\includegraphics[width=3cm]{deptlogo.pdf} \\
\begin{footnotesize}
This project is supported by the Australian National Data Service through the National Collaborative Research Infrastructure Strategy Program and the Education Investment Fund (EIF) Super Science Initiative.

More information from \texttt{ivan.hanigan@gmail.com} or at \texttt{http://opensoftware-restricteddata.github.io}

\end{footnotesize}

* References
** References
\begin{footnotesize}
\begin{thebibliography}{1}

\bibitem{Peng2011}
Roger~D Peng.
\newblock {Reproducible research in computational science.}
\newblock {\em Science (New York, N.Y.)}, 334(6060):1226--7, December 2011.

\bibitem{Hanigan2012b}
I.~C. Hanigan, C.~D. Butler, P.~N. Kokic, and M.~F. Hutchinson.
\newblock {Suicide and drought in New South Wales, Australia, 1970-2007}.
\newblock {\em Proceedings of the National Academy of Sciences}, pages
  1112965109--, August 2012.

\bibitem{Climate2008}
Hilary~J Bambrick, Keith B~G Dear, RE~Woodruff, Ivan~Charles Hanigan, and
  Anthony~J McMichael.
\newblock {The impacts of climate change on three health outcomes:
  temperature-related mortality and hospitalisations, salmonellosis and other
  bacterial gastroenteritis, and population at risk from dengue.}
\newblock Technical report, Garnaut Climate Change Review, Canberra, 2008.

\end{thebibliography}
\end{footnotesize}
